# SPDX-License-Identifier: LGPL-2.1-or-later

[Build]
CacheDirectory=mkosi.cache
History=yes
ToolsTree=default
ToolsTreeRelease=trixie
ToolsTreePackages=
    uuid
    debsums
Incremental=no
BuildSources=.
BuildSourcesEphemeral=yes
Environment=
    CLOUD_BUILD_OUTPUT_DIR
    CLOUD_BUILD_NAME
    CLOUD_RELEASE_ID
    CLOUD_RELEASE_VERSION
    SEED_UUID

[Content]
SELinuxRelabel=no
ShimBootloader=none
UnifiedKernelImages=no

[Content]
# Base package set installed everywhere (oci images, vm images, etc)
Packages=
        apt
        bash
        diffutils
        grep
        gzip
        sed
        util-linux
        login
        mount
        passwd
        tzdata
