#!/usr/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later

[ -d "${BUILDROOT}/etc" ] || exit 0

cat <<EOF > "${BUILDROOT}/etc/cloud-release"
ID=$CLOUD_RELEASE_ID
VERSION="$CLOUD_RELEASE_VERSION"
EOF
