[Match]
Format=|tar
Format=|disk
Format=|directory

[Output]
# We don't compress the output here, since we're generating a tarball that will
# be consumed directly, and compression just adds overhead
CompressOutput=no

# Disable mkosi's bootloader installation/configuration, as it does not result
# in the configuration that we expect in the Debian images.
[Content]
Bootable=no
Bootloader=none
ShimBootloader=none
BiosBootloader=none

[Content]
Packages=
    e2fsprogs
    nano
    dracut
    sudo
    less
    libpam-systemd
    systemd-resolved
    systemd-repart
    libnss-resolve
    libnss-myhostname
    netplan.io
    polkitd
    unattended-upgrades
    apparmor
    zstd
    apt-utils
    init
    iptables
    iputils-ping
    linux-sysctl-defaults
    nano
    netbase
    vim-tiny
    whiptail
    systemd
    udev
    kmod
    openssh-server
    openssh-client
    ssh-import-id
    bash-completion
    dbus-broker
    iproute2
    login
    polkitd
    systemd-coredump
    tzdata
